// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tormttwtzfanaqghvfuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvcm10dHd0emZhbmFxZ2h2ZnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTQwNDIsImV4cCI6MjA2NzIzMDA0Mn0.q3_maAgXLbOA68B1XaKM1eD1b161QD4Pl-r6N-i-IBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});